version: '3.8'

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik_desarrollo
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_desarrollo
    working_dir: /var/www/laravel
    volumes:
      - ./laravel:/var/www/laravel
    command: php artisan serve --host=0.0.0.0 --port=8000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=Host(`localhost`)"
      - "traefik.http.routers.laravel.entrypoints=web"
      - "traefik.http.services.laravel.loadbalancer.server.port=8000"
      - "traefik.http.routers.vite.rule=Host(`localhost`) && PathPrefix(`/@vite`)"
      - "traefik.http.routers.vite.entrypoints=web"
      - "traefik.http.services.vite.loadbalancer.server.port=5173"
    ports:
      - "8000:8000"   # para el servidor de Laravel
      - "5173:5173"   # para el Vite dev server
    depends_on:
      - mysql
    networks:
      - app-network


  mysql:
    image: mysql:8.0
    container_name: laravel_mysql_desarrollo
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin_desarrollo
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8080:80"
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
